# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-27 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_detail',
            field=models.CharField(blank=True, max_length=100, verbose_name='User Detail'),
        ),
    ]
