# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-24 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.SlugField(blank=True, help_text='This name is auto generated from the name and reference ID. It is used to make it easy to find the animal in a URL lookup.', max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('cat_type', models.CharField(choices=[('O', 'Orphan'), ('P', 'Pregnant'), ('N', 'Nursing')], default='O', max_length=1)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('weight_unit', models.CharField(choices=[('ML', '(ml) Milliliters'), ('CC', '(cc) Cubic Centimeters'), ('OZ', '(oz) Ounces'), ('LB', '(lb) Pounds'), ('G', '(G) Grams')], default='G', max_length=2)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='kitty_photos')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('alert_feeder', models.BooleanField(default=False, help_text='Alert feeder to critical situations')),
                ('critical_notes', models.TextField(blank=True, null=True)),
                ('first_weight_loss', models.BooleanField(default=False)),
                ('second_weight_loss', models.BooleanField(default=False)),
                ('third_weight_loss', models.BooleanField(default=False)),
                ('many_weight_losses', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_unit_measure', models.CharField(choices=[('ML', '(ml) Milliliters'), ('CC', '(cc) Cubic Centimeters'), ('OZ', '(oz) Ounces'), ('LB', '(lb) Pounds'), ('G', '(G) Grams')], default='G', max_length=2)),
                ('weight_before_food', models.IntegerField(blank=True, null=True)),
                ('food_unit_measure', models.CharField(choices=[('ML', '(ml) Milliliters'), ('CC', '(cc) Cubic Centimeters'), ('OZ', '(oz) Ounces'), ('LB', '(lb) Pounds'), ('G', '(G) Grams')], default='G', max_length=2)),
                ('amount_of_food_taken', models.IntegerField(blank=True, null=True)),
                ('food_type', models.CharField(choices=[('NA', 'None / Not Entered'), ('BO', 'Bottle'), ('BS', 'Bottle / Syringe'), ('SG', 'Syringe Gruel'), ('GG', 'Syringe Gruel / Gruel'), ('G', 'Gruel')], default='NA', max_length=2)),
                ('weight_after_food', models.IntegerField(blank=True, null=True)),
                ('stimulated', models.BooleanField(default=False)),
                ('stimulation_type', models.CharField(choices=[('NA', 'None / Not Entered'), ('UR', 'Urine'), ('FE', 'Feces'), ('UF', 'Urine / Feces')], default='NA', max_length=2)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='kitty_photos')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Cat')),
            ],
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_given', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('vet_practice', models.CharField(max_length=100)),
                ('doc_name', models.CharField(max_length=100)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Cat')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(max_length=2)),
                ('dosage_unit', models.CharField(default='ML', max_length=2)),
                ('dosage', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Cat')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='litter_mates',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracker.Litter'),
        ),
    ]
