# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-24 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='litter_mates',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='litter_mates', to='tracker.Litter'),
        ),
    ]
