# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-26 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
