# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-03 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_cat_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
