# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-24 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180624_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='litter_mates',
        ),
        migrations.AddField(
            model_name='cat',
            name='litter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracker.Litter'),
        ),
    ]
