# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-16 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_cat_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(max_length=2)),
                ('dosage_unit', models.CharField(default='ML', max_length=2)),
                ('dosage', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Cat')),
            ],
        ),
    ]
