# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-25 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_cat_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litter',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
