# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-26 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_given', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('vet_practice', models.CharField(max_length=100)),
                ('doc_name', models.CharField(max_length=100)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Cat')),
            ],
        ),
    ]
