# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-26 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_medicalrecords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalRecords',
            new_name='MedicalRecord',
        ),
    ]
