# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-25 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20180624_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='litter',
        ),
        migrations.AddField(
            model_name='cat',
            name='litter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='litter',
            name='cat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
