# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-25 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20180624_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='litter_name',
            new_name='litter_mates',
        ),
    ]
