# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-22 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20180325_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='cat_type',
            field=models.CharField(choices=[('O', 'Orphan'), ('P', 'Pregnant'), ('N', 'Nursing')], default='O', max_length=1),
        ),
    ]
