# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-30 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20180624_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='litter',
            old_name='cat',
            new_name='litter_name',
        ),
        migrations.RenameField(
            model_name='litter',
            old_name='name',
            new_name='mom_cat',
        ),
        migrations.AlterField(
            model_name='feeding',
            name='food_type',
            field=models.CharField(choices=[('NA', 'None / Not Entered'), ('MN', 'Mom (Nursing)'), ('BO', 'Bottle'), ('BS', 'Bottle / Syringe'), ('SG', 'Syringe Gruel'), ('GG', 'Syringe Gruel / Gruel'), ('G', 'Gruel')], default='NA', max_length=2),
        ),
    ]
