# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-07 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20180630_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='showRow',
            field=models.BooleanField(default=False),
        ),
    ]
