# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-22 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20180622_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='litter',
        ),
        migrations.AddField(
            model_name='cat',
            name='litter',
            field=models.ManyToManyField(to='tracker.Litter'),
        ),
    ]
