# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-07 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_medication_showrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='showRow',
            field=models.BooleanField(default=True),
        ),
    ]
