# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-23 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20180622_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='litter',
        ),
        migrations.AddField(
            model_name='litter',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='litter_mates', to='tracker.Cat'),
        ),
    ]
