# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-07 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20180707_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='showRow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feeding',
            name='showRow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='litter',
            name='showRow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='showRow',
            field=models.BooleanField(default=True),
        ),
    ]
