# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-07 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20180707_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='showRow',
        ),
    ]
