# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-05 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_medication_showrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_type',
            field=models.CharField(choices=[('O', 'Orphan'), ('P', 'Pregnant'), ('NK', 'Nursing Kitten'), ('NM', 'Nursing Mom'), ('A', 'Adult')], default='O', max_length=1),
        ),
    ]
