# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-05 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20180805_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
