# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-19 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_autoslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0014_auto_20180805_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True)),
                ('weight_unit_measure', models.CharField(choices=[('ML', '(ml) Milliliters'), ('CC', '(cc) Cubic Centimeters'), ('OZ', '(oz) Ounces'), ('LB', '(lb) Pounds'), ('G', '(G) Grams')], default='G', max_length=2)),
                ('weight_before_food', models.IntegerField(blank=True, null=True)),
                ('food_unit_measure', models.CharField(choices=[('ML', '(ml) Milliliters'), ('CC', '(cc) Cubic Centimeters'), ('OZ', '(oz) Ounces'), ('LB', '(lb) Pounds'), ('G', '(G) Grams')], default='G', max_length=2)),
                ('amount_of_food_taken', models.IntegerField(blank=True, null=True)),
                ('food_type', models.CharField(blank=True, choices=[('MN', 'Mom (Nursing)'), ('BO', 'Bottle'), ('BS', 'Bottle / Syringe'), ('SG', 'Syringe Gruel'), ('GG', 'Syringe Gruel / Gruel'), ('G', 'Gruel')], max_length=2, null=True)),
                ('weight_after_food', models.IntegerField(blank=True, null=True)),
                ('stimulated', models.BooleanField(default=False)),
                ('stimulation_type', models.CharField(blank=True, choices=[('UR', 'Urine'), ('FE', 'Feces'), ('UF', 'Urine / Feces')], max_length=2, null=True)),
                ('medication_dosage_given', models.FloatField(blank=True, null=True)),
                ('medication_dosage_unit', models.CharField(blank=True, choices=[('ML', '(ml) Milliliters'), ('CC', '(cc) Cubic Centimeters'), ('OZ', '(oz) Ounces'), ('LB', '(lb) Pounds'), ('G', '(G) Grams')], help_text='If left blank this will default to the default unit for the medication.', max_length=2, null=True)),
                ('notes', models.CharField(blank=True, max_length=2048, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='kitty_photos')),
            ],
        ),
        migrations.CreateModel(
            name='FosterAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('slug', django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True)),
                ('severity', models.CharField(choices=[('0', 'Notice'), ('1', 'Warning'), ('2', 'Danger'), ('3', 'Critical'), ('4', 'Emergency')], default='0', max_length=1)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('received_on', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VetVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True)),
                ('care_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('care_details', models.TextField(blank=True, null=True)),
                ('appointment', models.DateTimeField(auto_now_add=True)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('practice_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='kitty_photos')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='cat',
        ),
        migrations.RenameField(
            model_name='litter',
            old_name='litter_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='age',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='alert_feeder',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='critical_notes',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='litter_mates',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='showRow',
        ),
        migrations.RemoveField(
            model_name='litter',
            name='mom_cat',
        ),
        migrations.RemoveField(
            model_name='litter',
            name='showRow',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='showRow',
        ),
        migrations.AddField(
            model_name='cat',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cat',
            name='adoption_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='foster_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cat',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Litter'),
        ),
        migrations.AddField(
            model_name='litter',
            name='foster_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='litter',
            name='slug',
            field=django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage_guidelines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='package_photo_1',
            field=models.FileField(blank=True, null=True, upload_to='medication_package_photos'),
        ),
        migrations.AddField(
            model_name='medication',
            name='package_photo_2',
            field=models.FileField(blank=True, null=True, upload_to='medication_package_photos'),
        ),
        migrations.AddField(
            model_name='medication',
            name='package_photo_3',
            field=models.FileField(blank=True, null=True, upload_to='medication_package_photos'),
        ),
        migrations.AddField(
            model_name='medication',
            name='slug',
            field=django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='slug',
            field=django_autoslugfield.fields.AutoSlugField(blank=True, max_length=255, null=True, title_field=None, unique=True),
        ),
        migrations.AlterField(
            model_name='litter',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage_unit',
            field=models.CharField(blank=True, choices=[('ML', '(ml) Milliliters'), ('CC', '(cc) Cubic Centimeters'), ('OZ', '(oz) Ounces'), ('LB', '(lb) Pounds'), ('G', '(G) Grams')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Feeding',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.AddField(
            model_name='vetvisit',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Cat'),
        ),
        migrations.AddField(
            model_name='vetvisit',
            name='foster_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fosteralert',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Cat'),
        ),
        migrations.AddField(
            model_name='fosteralert',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foster_alert_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fosteralert',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foster_alert_received_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carelog',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Cat'),
        ),
        migrations.AddField(
            model_name='carelog',
            name='foster_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carelog',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Medication'),
        ),
    ]
