# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-19 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20180819_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carelog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='litter',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
