# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-27 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20180819_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='fosteralert',
            name='user_detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='User Detail'),
            preserve_default=False,
        ),
    ]
