# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-28 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20180805_1803'),
        ('tracker', '0017_auto_20180819_1049'),
    ]

    operations = [
    ]
