# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-27 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_fosteralert_user_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fosteralert',
            name='user_detail',
        ),
    ]
