# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-28 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_remove_fosteralert_user_detail'),
        ('tracker', '0019_auto_20180828_0251'),
    ]

    operations = [
    ]
