# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-15 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_merge_20180828_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carelog',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Medication'),
        ),
    ]
