# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-17 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_auto_20180914_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carelog',
            name='weight_after_food',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
